export type BrowserKind = "netscape" | "ie" | "firefox" | "chrome" | "edge";

export type Category =
  | "search"
  | "social"
  | "entertainment"
  | "technology"
  | "shopping"
  | "knowledge"
  | "os";

export const CATEGORY_LABEL: Record<Category, string> = {
  search: "Search",
  social: "Social",
  entertainment: "Entertainment",
  technology: "Technology",
  shopping: "Shopping",
  knowledge: "Knowledge",
  os: "Operating Systems",
};

export interface EraSnapshot {
  year: number;
  url: string;
  browser: BrowserKind;
  tagline: string;
  whatChanged: string;
  designTrend: string;
  whyItMattered: string;
  facts: string[];
  tech: string[];
}

export interface SiteDef {
  id: string;
  name: string;
  category: Category;
  founded: string;
  foundedYear: number;
  /** Brand ink used for the card mark. Historical brand colours, not app theming. */
  brand: string;
  mark: string;
  blurb: string;
  snapshots: EraSnapshot[];
}

const era = (
  year: number,
  url: string,
  browser: BrowserKind,
  tagline: string,
  whatChanged: string,
  designTrend: string,
  whyItMattered: string,
  facts: string[],
  tech: string[],
): EraSnapshot => ({
  year,
  url,
  browser,
  tagline,
  whatChanged,
  designTrend,
  whyItMattered,
  facts,
  tech,
});

export const SITES: SiteDef[] = [
  {
    id: "google",
    name: "Google",
    category: "search",
    founded: "September 4, 1998",
    foundedYear: 1998,
    brand: "#4285f4",
    mark: "G",
    blurb: "From a Stanford research page to an answer engine.",
    snapshots: [
      era(
        1998,
        "http://google.stanford.edu",
        "netscape",
        "A beta search box on a Stanford server.",
        "Search stopped being a directory and became a ranked list.",
        "Bare HTML, centred tables, one exclamation mark.",
        "PageRank proved links were votes, and relevance beat curation.",
        [
          "The homepage was bare because the founders barely knew HTML.",
          "The exclamation mark was a Yahoo!-era habit.",
          "No Gmail, no Maps, no ads — just ten blue links.",
        ],
        ["HTML 3.2", "CGI", "Tables"],
      ),
      era(
        2004,
        "http://www.google.com",
        "ie",
        "Tabs above the box, Gmail in invite-only beta.",
        "Google became a suite instead of a single page.",
        "Text tabs, 10px Arial, nested table layouts.",
        "Free webmail with a gigabyte of storage reset user expectations.",
        [
          "Gmail launched April 1, 2004 and people assumed it was a prank.",
          "Image and Groups search sat as plain text tabs.",
          "Everything still rendered inside nested <table> layouts.",
        ],
        ["HTML 4.01", "Tables", "JavaScript 1.5"],
      ),
      era(
        2010,
        "https://www.google.com",
        "firefox",
        "Instant results type themselves as you type.",
        "The page stopped reloading — results streamed live.",
        "Fade-in chrome, a black utility bar, soft gradients.",
        "AJAX search made the browser feel like an application.",
        [
          "Google Instant streamed results on every keystroke.",
          "The homepage faded its buttons in on mouse movement.",
          "The black top bar unified Search, Images, Maps and YouTube.",
        ],
        ["AJAX", "CSS 2.1", "XHTML"],
      ),
      era(
        2016,
        "https://www.google.com",
        "chrome",
        "Material Design, flat colours, one rounded pill.",
        "Search became mobile-first and card-shaped.",
        "Flat colour, elevation shadows, geometric sans.",
        "Mobile-first indexing reshaped how the entire web was built.",
        [
          "The logo was redrawn in the geometric sans Product Sans.",
          "Mobile-first indexing began reshaping the whole web.",
          "The search box became a floating card with a soft shadow.",
        ],
        ["Material Design", "Flexbox", "Responsive"],
      ),
      era(
        2026,
        "https://www.google.com",
        "edge",
        "An AI overview answers before the links load.",
        "The answer moved above the links.",
        "Generous whitespace, adaptive dark mode, soft pill inputs.",
        "Synthesis replaced navigation as the default search outcome.",
        [
          "Generated summaries sit above the classic result list.",
          "Dark mode is system-adaptive rather than a toggle.",
          "Voice and multimodal search live inside the same pill.",
        ],
        ["AI Overviews", "CSS Grid", "Container Queries"],
      ),
    ],
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "entertainment",
    founded: "February 14, 2005",
    foundedYear: 2005,
    brand: "#ff0000",
    mark: "▶",
    blurb: "A video dating site that accidentally ate television.",
    snapshots: [
      era(
        2005,
        "http://www.youtube.com",
        "ie",
        "Tune in. Hook up. A dating site that pivoted.",
        "Uploading video became a two-click act.",
        "Blue gradients, 11px Verdana, table shelves.",
        "Video stopped being a download and became a page you shared.",
        [
          "The original tagline really was 'Broadcast Yourself'.",
          "Videos were 320x240 Flash at a glorious 240p.",
          "Me at the zoo was 18 seconds long and changed everything.",
        ],
        ["Flash 7", "Tables", "PHP"],
      ),
      era(
        2012,
        "https://www.youtube.com",
        "chrome",
        "Cosmic Panda greys and a left-hand guide.",
        "Channels replaced profiles; the guide became permanent.",
        "Grey chrome, thin dividers, fixed-width columns.",
        "Creators became the product, and subscriptions became the feed.",
        [
          "The watch page moved to a fixed-width dark surround.",
          "Channels replaced the old user profile pages.",
          "HTML5 video began quietly replacing Flash.",
        ],
        ["HTML5 Video", "Floats", "AJAX"],
      ),
      era(
        2020,
        "https://www.youtube.com",
        "chrome",
        "Dark mode, cards, infinite grid.",
        "The homepage became an algorithmic grid.",
        "Card surfaces, 16:9 thumbnails, dark theme.",
        "Recommendation replaced search as the way most video is found.",
        [
          "Polymer web components rebuilt the entire front end.",
          "Dark theme shipped natively in 2017.",
          "Thumbnails grew to 16:9 cards on a fluid grid.",
        ],
        ["Web Components", "CSS Grid", "Dark Mode"],
      ),
      era(
        2026,
        "https://www.youtube.com",
        "edge",
        "Shorts rail, AI chapters, ambient glow.",
        "Short vertical video shares the shelf with long-form.",
        "Ambient colour bleed, rounded surfaces, chaptered players.",
        "Attention split into two formats living on one page.",
        [
          "Ambient mode bleeds the video's colours into the page.",
          "Auto-generated chapters and summaries sit under the player.",
          "Vertical Shorts share the shelf with classic long-form video.",
        ],
        ["AI Chapters", "Container Queries", "AV1"],
      ),
    ],
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    category: "knowledge",
    founded: "January 15, 2001",
    foundedYear: 2001,
    brand: "#3366cc",
    mark: "W",
    blurb: "The encyclopedia anyone could break, and everyone fixed.",
    snapshots: [
      era(
        2001,
        "http://www.wikipedia.com",
        "netscape",
        "A plain wiki with a promise to be an encyclopedia.",
        "Editing moved from experts to anyone with a browser.",
        "Times New Roman, blue links, zero chrome.",
        "Open editing proved crowds could out-produce publishers.",
        [
          "The first version ran on UseModWiki with CamelCase links.",
          "It reached 20,000 articles in its first year.",
          "There was no logo — just a heading and a list.",
        ],
        ["Perl", "UseModWiki", "HTML 4"],
      ),
      era(
        2008,
        "http://en.wikipedia.org",
        "firefox",
        "Monobook: the sidebar everyone remembers.",
        "Structure arrived: tabs, sidebar, infoboxes, citations.",
        "Pale blue chrome, serif headings, dense body text.",
        "Consistent navigation made a million pages feel like one book.",
        [
          "The Monobook skin lasted from 2004 to 2010.",
          "Tabs across the top: article, discussion, edit, history.",
          "Serif headings over a pale blue chrome.",
        ],
        ["Monobook", "CSS 2", "PHP"],
      ),
      era(
        2026,
        "https://en.wikipedia.org",
        "edge",
        "Vector 2022: narrow measure, sticky tools.",
        "Reading comfort finally beat information density.",
        "Capped line length, sticky table of contents, dark mode.",
        "Typography became an accessibility decision, not decoration.",
        [
          "Line length is capped for readability on wide screens.",
          "The table of contents follows you down the page.",
          "Dark mode arrived after two decades of white pages.",
        ],
        ["Vector 2022", "CSS Grid", "Dark Mode"],
      ),
    ],
  },
  {
    id: "amazon",
    name: "Amazon",
    category: "shopping",
    founded: "July 5, 1994",
    foundedYear: 1994,
    brand: "#ff9900",
    mark: "a",
    blurb: "Earth's biggest bookstore, then earth's biggest everything.",
    snapshots: [
      era(
        1999,
        "http://www.amazon.com",
        "netscape",
        "Earth's biggest bookstore, in 216 web-safe colours.",
        "Shopping tabs organised a catalogue that outgrew books.",
        "Web-safe palette, GIF spacers, tabbed table nav.",
        "1-Click ordering made friction the enemy of commerce.",
        [
          "The site was mostly books, music and a new 'toys' tab.",
          "1-Click ordering was patented in 1999.",
          "Everything was laid out in tables with GIF spacers.",
        ],
        ["Tables", "GIF spacers", "Perl"],
      ),
      era(
        2010,
        "https://www.amazon.com",
        "firefox",
        "Orange gradients, dense shelves, Prime everywhere.",
        "Recommendations became the storefront.",
        "Gradient buttons, dense shelves, hover mega-menus.",
        "Personalisation drove roughly a third of all sales.",
        [
          "Departments moved into a hover mega-menu.",
          "Recommendations drove roughly a third of sales.",
          "The buy box gradient became the most copied button on the web.",
        ],
        ["CSS Sprites", "AJAX", "Floats"],
      ),
      era(
        2026,
        "https://www.amazon.com",
        "chrome",
        "Dark navigation, card grids, AI review digests.",
        "Reviews are summarised rather than read.",
        "Responsive card grid, dark utility nav, generated copy.",
        "Trust signals became machine-written for the first time.",
        [
          "Review summaries are generated rather than read.",
          "The layout is a responsive grid instead of a fixed 1000px.",
          "Same-day delivery promises are rendered per postcode.",
        ],
        ["CSS Grid", "AI Summaries", "Responsive"],
      ),
    ],
  },
  {
    id: "facebook",
    name: "Facebook",
    category: "social",
    founded: "February 4, 2004",
    foundedYear: 2004,
    brand: "#1877f2",
    mark: "f",
    blurb: "A campus directory that became the world's front page.",
    snapshots: [
      era(
        2004,
        "http://www.thefacebook.com",
        "ie",
        "Thefacebook: a directory for college students.",
        "Real names replaced pseudonyms online.",
        "Blue banner, Al Pacino silhouette, plain forms.",
        "Identity became the primary key of the social web.",
        [
          "You needed a .edu email address to register.",
          "The masthead silhouette was widely believed to be Al Pacino.",
          "There was no news feed — you visited profiles one by one.",
        ],
        ["PHP", "Tables", "MySQL"],
      ),
      era(
        2008,
        "http://www.facebook.com",
        "firefox",
        "The News Feed and the two-column profile.",
        "Content came to you instead of you visiting profiles.",
        "Two columns, tabbed profiles, 11px Lucida Grande.",
        "The feed invented the infinite scroll of everyone's life.",
        [
          "The 2008 redesign moved the wall into tabs and caused riots.",
          "Poking had no defined purpose and everyone did it anyway.",
          "Applications and quizzes flooded the platform.",
        ],
        ["XHTML", "AJAX", "FBML"],
      ),
      era(
        2012,
        "https://www.facebook.com",
        "chrome",
        "Timeline, cover photos, mobile-first pivot.",
        "Profiles became autobiographies with cover art.",
        "Big cover images, card stories, blue chrome.",
        "The IPO year forced a rebuild around mobile screens.",
        [
          "Timeline reframed your profile as a scrollable life story.",
          "Facebook hit one billion users in October 2012.",
          "The mobile app was rewritten from HTML5 to native.",
        ],
        ["HTML5", "Timeline", "Open Graph"],
      ),
      era(
        2018,
        "https://www.facebook.com",
        "chrome",
        "Rounded cards, reactions, stories at the top.",
        "One like became six reactions.",
        "White cards, rounded corners, softer type.",
        "Emotional granularity became a ranking signal.",
        [
          "Reactions gave the algorithm five more signals than a like.",
          "Stories borrowed the format from Snapchat.",
          "News Feed began demoting publishers in favour of friends.",
        ],
        ["React", "GraphQL", "Cards"],
      ),
      era(
        2026,
        "https://www.facebook.com",
        "edge",
        "Dark surfaces, AI feeds, video-first shelves.",
        "The friend graph is mostly a recommendation engine now.",
        "Dark neutral surfaces, dense video rails, quiet chrome.",
        "Social became broadcast, and feeds became television.",
        [
          "Most feed content comes from accounts you do not follow.",
          "Short video occupies more of the feed than status text.",
          "The blue is muted for dark surfaces.",
        ],
        ["React", "AI Ranking", "Dark Mode"],
      ),
    ],
  },
  {
    id: "reddit",
    name: "Reddit",
    category: "social",
    founded: "June 23, 2005",
    foundedYear: 2005,
    brand: "#ff4500",
    mark: "r",
    blurb: "The front page of the internet, stubbornly text-shaped.",
    snapshots: [
      era(
        2005,
        "http://reddit.com",
        "firefox",
        "A link list with arrows and nothing else.",
        "Voting replaced editors.",
        "Verdana, arrow GIFs, near-zero styling.",
        "Ranking by votes turned a link dump into a newspaper.",
        [
          "The first version was written in Lisp.",
          "Early accounts were fake, created by the founders to seed content.",
          "The alien mascot Snoo was sketched during a lecture.",
        ],
        ["Lisp", "HTML 4", "CSS 1"],
      ),
      era(
        2010,
        "http://www.reddit.com",
        "chrome",
        "Subreddits, karma, and the great blue links.",
        "Communities became user-created and self-governed.",
        "Dense list rows, tiny type, orange accents.",
        "Moderation moved from staff to volunteers at scale.",
        [
          "Anyone could create a subreddit from 2008 onward.",
          "The site ran on a handful of servers and fell over often.",
          "Reddit Gold launched to pay the hosting bill.",
        ],
        ["Python", "Pylons", "CSS 2"],
      ),
      era(
        2016,
        "https://www.reddit.com",
        "chrome",
        "Old Reddit at its densest: 40 links per screen.",
        "Nothing changed visually for a decade, on purpose.",
        "Information density over hierarchy.",
        "Proof that a community will defend an ugly interface.",
        [
          "Users still browse old.reddit.com today.",
          "Comment threads collapse into infinitely nested trees.",
          "Custom subreddit CSS made every community look different.",
        ],
        ["jQuery", "CSS 2", "Server rendering"],
      ),
      era(
        2026,
        "https://www.reddit.com",
        "edge",
        "Card feed, inline media, rounded everything.",
        "Cards and media previews replaced the raw link list.",
        "Rounded cards, avatars, generous spacing.",
        "Legibility won, but density loyalists never left.",
        [
          "The card feed doubled the vertical space per post.",
          "Avatars and profiles borrowed from mainstream social.",
          "Old Reddit remains available and widely used.",
        ],
        ["React", "GraphQL", "Design tokens"],
      ),
    ],
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "entertainment",
    founded: "August 29, 1997",
    foundedYear: 1997,
    brand: "#e50914",
    mark: "N",
    blurb: "Red envelopes to an algorithmic wall of thumbnails.",
    snapshots: [
      era(
        2003,
        "http://www.netflix.com",
        "ie",
        "DVDs by mail and a queue you managed by hand.",
        "Rental late fees disappeared.",
        "Red and white tables, box-art thumbnails, Verdana.",
        "Subscription replaced the transaction as the media business model.",
        [
          "Your queue was a numbered list you reordered by typing numbers.",
          "Cinematch recommended discs based on star ratings.",
          "Shipping centres were listed by city on the site.",
        ],
        ["Tables", "JSP", "GIF"],
      ),
      era(
        2007,
        "http://www.netflix.com",
        "firefox",
        "Watch Instantly arrives with a Silverlight player.",
        "Streaming appeared as a tab next to the DVD queue.",
        "Gradients, rounded tabs, glossy buttons.",
        "The first hour of streaming quietly ended the disc era.",
        [
          "Streaming launched with about 1,000 titles.",
          "Playback required a browser plugin on Windows only.",
          "Hours were rationed by your subscription tier.",
        ],
        ["Silverlight", "AJAX", "CSS 2"],
      ),
      era(
        2013,
        "https://www.netflix.com",
        "chrome",
        "House of Cards and the endless horizontal row.",
        "Browsing became sideways scrolling through rows.",
        "Dark UI, big box art, hover expansion.",
        "Original programming turned a distributor into a studio.",
        [
          "All thirteen episodes dropped at once and coined binge-watching.",
          "Rows were personalised per profile, not per account holder.",
          "The interface went dark to make artwork pop.",
        ],
        ["HTML5 Video", "Backbone", "CSS 3"],
      ),
      era(
        2018,
        "https://www.netflix.com",
        "chrome",
        "Autoplaying billboards and per-title artwork tests.",
        "Artwork itself became personalised and A/B tested.",
        "Full-bleed hero video, hover previews, tight rows.",
        "The thumbnail became the most optimised pixel in media.",
        [
          "Netflix generated dozens of artwork variants per title.",
          "Trailers autoplayed on hover, then on focus.",
          "Profiles gained kid-safe modes and separate rows.",
        ],
        ["React", "Node", "A/B testing"],
      ),
      era(
        2026,
        "https://www.netflix.com",
        "edge",
        "Ad tiers, live events, AI-written row titles.",
        "Rows are generated per session rather than per profile.",
        "Cinematic dark surfaces, motion-lite hero, quiet chrome.",
        "Personalisation reached the level of individual sentences.",
        [
          "Row titles are generated text rather than fixed categories.",
          "Live events sit alongside on-demand rows.",
          "Ad-supported tiers reshaped the pricing page.",
        ],
        ["Server components", "AV1", "AI Metadata"],
      ),
    ],
  },
  {
    id: "github",
    name: "GitHub",
    category: "technology",
    founded: "April 10, 2008",
    foundedYear: 2008,
    brand: "#24292f",
    mark: "◱",
    blurb: "Version control turned into a social network for builders.",
    snapshots: [
      era(
        2008,
        "http://github.com",
        "firefox",
        "Social coding, in beige and blue.",
        "Git got a face, and forking became a compliment.",
        "Beige textures, rounded boxes, Helvetica stacks.",
        "Open source collaboration moved from mailing lists to pull requests.",
        [
          "The tagline was literally 'social coding'.",
          "Private repositories were the only paid feature.",
          "The Octocat was licensed art, redrawn later.",
        ],
        ["Rails", "CSS 2", "Git"],
      ),
      era(
        2012,
        "https://github.com",
        "chrome",
        "The pull request becomes the unit of work.",
        "Code review moved inline, line by line.",
        "Grey chrome, file tables, monospace everywhere.",
        "PR review became the default workflow of software teams.",
        [
          "Inline diff comments changed how teams reviewed code.",
          "GitHub Pages made static hosting free.",
          "The contribution graph turned commits into a game.",
        ],
        ["Rails", "jQuery", "SCSS"],
      ),
      era(
        2016,
        "https://github.com",
        "chrome",
        "A flatter, lighter, enterprise-ready interface.",
        "Issues, projects and reviews became first-class.",
        "Flat surfaces, blue primary buttons, tighter grid.",
        "Project management folded into the code host.",
        [
          "Reviews got explicit approve and request-changes states.",
          "Protected branches arrived for teams.",
          "The redesign dropped nearly all texture and gradient.",
        ],
        ["Rails", "Primer CSS", "PJAX"],
      ),
      era(
        2020,
        "https://github.com",
        "chrome",
        "Dark mode, Actions, and a rebuilt code view.",
        "CI moved inside the repository.",
        "Design tokens, dark theme, dense monospace.",
        "The repo became the whole software factory.",
        [
          "GitHub Actions replaced a generation of external CI services.",
          "Dark mode shipped as an official theme in December 2020.",
          "Codespaces put the editor in the browser.",
        ],
        ["Primer", "Web Components", "Actions"],
      ),
      era(
        2026,
        "https://github.com",
        "edge",
        "AI review, agent panels, code as conversation.",
        "Assistants sit inside the diff.",
        "Calm neutral surfaces, panel layouts, subtle motion.",
        "Authoring and reviewing code became a dialogue.",
        [
          "Suggested patches arrive before a human opens the file.",
          "Agents open their own pull requests.",
          "The code view is a resizable multi-pane workspace.",
        ],
        ["React", "AI Review", "Design tokens"],
      ),
    ],
  },
  {
    id: "yahoo",
    name: "Yahoo!",
    category: "search",
    founded: "January 1994",
    foundedYear: 1994,
    brand: "#7b0099",
    mark: "Y!",
    blurb: "A hand-made directory that tried to be everything.",
    snapshots: [
      era(
        1996,
        "http://www.yahoo.com",
        "netscape",
        "A human-edited directory of the entire web.",
        "The web was small enough to list by hand.",
        "Purple links, Times New Roman, bullet lists.",
        "Curation was briefly a viable way to organise the internet.",
        [
          "Categories were maintained by human editors called surfers.",
          "The name stood for Yet Another Hierarchical Officious Oracle.",
          "New sites were marked with a small NEW! flame GIF.",
        ],
        ["HTML 2", "CGI", "Perl"],
      ),
      era(
        2000,
        "http://www.yahoo.com",
        "ie",
        "The portal era: mail, news, chat, stocks, all at once.",
        "The homepage became a dashboard of everything.",
        "Dense link columns, purple headings, tiny Arial.",
        "Portals monetised attention before search ads existed.",
        [
          "Yahoo peaked at a $125 billion valuation in January 2000.",
          "Yahoo Mail, Messenger and GeoCities all lived under one nav.",
          "The homepage carried over 100 links above the fold.",
        ],
        ["Tables", "JavaScript", "Frames"],
      ),
      era(
        2005,
        "http://www.yahoo.com",
        "ie",
        "Rounded modules and a search box that fights back.",
        "Search moved to the centre as Google took the lead.",
        "Rounded module headers, gradient bars, blue links.",
        "The portal shrank as search became the front door.",
        [
          "Yahoo acquired Flickr and del.icio.us this year.",
          "Search results were powered by Yahoo's own index by then.",
          "Modules could be rearranged on My Yahoo.",
        ],
        ["AJAX", "CSS 2", "YUI"],
      ),
      era(
        2010,
        "http://www.yahoo.com",
        "firefox",
        "Personalised modules and a purple wordmark.",
        "Content became a river of headlines.",
        "Three-column layout, hover previews, softer purple.",
        "The last serious attempt at the portal as a habit.",
        [
          "The left rail let you preview services on hover.",
          "Yahoo News remained one of the largest news sites on earth.",
          "The exclamation mark stayed, against all advice.",
        ],
        ["jQuery", "CSS 2", "YUI 3"],
      ),
      era(
        2026,
        "https://www.yahoo.com",
        "chrome",
        "A news reader with a familiar purple heart.",
        "Yahoo settled into news, finance and mail.",
        "Clean cards, restrained purple, modern type.",
        "A reminder that surviving is its own kind of success.",
        [
          "Yahoo Finance remains a top destination for market data.",
          "Mail is still used by tens of millions of accounts.",
          "The purple is now a single accent instead of a whole page.",
        ],
        ["React", "CSS Grid", "Responsive"],
      ),
    ],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    category: "os",
    founded: "April 4, 1975",
    foundedYear: 1975,
    brand: "#0067b8",
    mark: "▦",
    blurb: "Windows on the desktop, and eventually on the web.",
    snapshots: [
      era(
        1995,
        "http://www.microsoft.com",
        "netscape",
        "Windows 95 launches and the Start button appears.",
        "The desktop metaphor got a taskbar and a Start menu.",
        "Grey 3D bevels, MS Sans Serif, teal wallpaper.",
        "It put a computer, and a modem, in ordinary homes.",
        [
          "The Start Me Up campaign cost a reported $300 million.",
          "Internet Explorer 1 shipped in the Plus! pack.",
          "The teal desktop became the most recognised screen on earth.",
        ],
        ["HTML 2", "Win32", "MS Sans Serif"],
      ),
      era(
        2000,
        "http://www.microsoft.com",
        "ie",
        "MSN, Hotmail and the blue-and-grey web.",
        "The company site became a portal in its own right.",
        "Blue gradient bars, bevelled buttons, Tahoma.",
        "Bundled browsers made distribution the whole strategy.",
        [
          "Internet Explorer held over 90% browser share.",
          "The antitrust ruling landed in April 2000.",
          "Hotmail was the largest webmail service in the world.",
        ],
        ["Tables", "ASP", "VBScript"],
      ),
      era(
        2005,
        "http://www.microsoft.com",
        "ie",
        "Windows XP everywhere: Luna blue and green hills.",
        "Consumer software went glossy and rounded.",
        "Luna blue chrome, glossy buttons, rounded panels.",
        "XP stayed on desktops for over a decade.",
        [
          "Bliss, the XP wallpaper, is an unedited photo of Sonoma County.",
          "XP shipped with a firewall off by default until SP2.",
          "The site pushed Windows Update as a habit.",
        ],
        ["CSS 2", "ASP.NET", "Luna theme"],
      ),
      era(
        2010,
        "http://www.microsoft.com",
        "firefox",
        "Metro arrives: type-first, flat, unapologetic.",
        "Chrome disappeared in favour of typography.",
        "Flat tiles, Segoe UI, no gradients at all.",
        "Metro pushed the entire industry toward flat design.",
        [
          "Metro was inspired by transit signage systems.",
          "Segoe UI became the face of the whole company.",
          "Flat design arrived here two years before iOS 7.",
        ],
        ["Segoe UI", "CSS 3", "Metro"],
      ),
      era(
        2026,
        "https://www.microsoft.com",
        "edge",
        "Fluent surfaces, Copilot everywhere.",
        "Assistants sit in the OS shell and the website.",
        "Soft depth, rounded corners, layered acrylic.",
        "The OS became a front-end for cloud models.",
        [
          "Fluent brought back depth without returning to skeuomorphism.",
          "Copilot entries appear on nearly every product page.",
          "Edge is Chromium underneath, which nobody predicted in 2005.",
        ],
        ["Fluent 2", "Web Components", "Copilot"],
      ),
    ],
  },
  {
    id: "apple",
    name: "Apple",
    category: "technology",
    founded: "April 1, 1976",
    foundedYear: 1976,
    brand: "#111111",
    mark: "",
    blurb: "Product photography as an entire design language.",
    snapshots: [
      era(
        1997,
        "http://www.apple.com",
        "netscape",
        "Think different, and please buy a Performa.",
        "The brand reset around a single idea.",
        "Grey backgrounds, small GIFs, Garamond headlines.",
        "The comeback that made design a business strategy.",
        [
          "Apple was reportedly 90 days from bankruptcy.",
          "Apple Garamond was the corporate typeface.",
          "The site sold beige towers alongside the new campaign.",
        ],
        ["HTML 3.2", "GIF", "Tables"],
      ),
      era(
        2001,
        "http://www.apple.com",
        "ie",
        "Aqua stripes, iPod, and glossy blue pills.",
        "Software UI became candy, and the web followed.",
        "Pinstripes, glossy Aqua buttons, drop shadows.",
        "1,000 songs in your pocket reframed the company.",
        [
          "Mac OS X shipped Aqua with real-time transparency.",
          "The iPod launched in October with a scroll wheel.",
          "The tab bar across the top lasted for over a decade.",
        ],
        ["Aqua", "Tables", "QuickTime"],
      ),
      era(
        2007,
        "http://www.apple.com",
        "firefox",
        "One product, one photograph, one sentence.",
        "The homepage became a poster.",
        "Full-bleed product shot, reflections, Myriad Pro.",
        "The iPhone made the mobile web unavoidable.",
        [
          "The iPhone launch page carried a single hero image.",
          "Reflections under products were the signature of the era.",
          "Flash was publicly refused on iOS in 2010.",
        ],
        ["Myriad Pro", "CSS 2", "QuickTime"],
      ),
      era(
        2013,
        "https://www.apple.com",
        "chrome",
        "Ultra-thin type, white space, scroll storytelling.",
        "Pages became scroll-driven narratives.",
        "Hairline type, enormous whitespace, staged reveals.",
        "Scrollytelling became the standard for product pages.",
        [
          "iOS 7 flattened a decade of skeuomorphism overnight.",
          "Helvetica Neue Ultra Light was criticised for legibility.",
          "Parallax product pages became an industry cliché.",
        ],
        ["Retina", "CSS 3", "Parallax"],
      ),
      era(
        2026,
        "https://www.apple.com",
        "edge",
        "Spatial renders, adaptive dark, calm motion.",
        "Product pages behave like short films.",
        "Adaptive dark surfaces, SF Pro, restrained motion.",
        "Restraint is still the loudest thing on the page.",
        [
          "Renders are increasingly interactive 3D rather than photos.",
          "Motion respects reduced-motion preferences by default.",
          "The nav bar has barely changed shape in fifteen years.",
        ],
        ["SF Pro", "WebGL", "Reduced motion"],
      ),
    ],
  },
  {
    id: "myspace",
    name: "MySpace",
    category: "social",
    founded: "August 1, 2003",
    foundedYear: 2003,
    brand: "#003399",
    mark: "M",
    blurb: "The last time the web let everyone break their own page.",
    snapshots: [
      era(
        2003,
        "http://www.myspace.com",
        "ie",
        "A profile, a song, and a background you chose.",
        "Personal expression beat consistency.",
        "Blue chrome, Verdana, tiled backgrounds.",
        "Millions of teenagers learned CSS by breaking their profile.",
        [
          "Profiles were customised by pasting CSS into a text box.",
          "Autoplaying music was the default, not the exception.",
          "Tom was everyone's first friend.",
        ],
        ["ColdFusion", "Tables", "Inline CSS"],
      ),
      era(
        2006,
        "http://www.myspace.com",
        "ie",
        "Top 8 drama and glittering GIF chaos.",
        "Friend ranking became a social weapon.",
        "Glitter GIFs, marquee text, clashing colours.",
        "It proved social networks are made of feelings, not features.",
        [
          "The Top 8 caused genuine, documented friendships to end.",
          "MySpace passed Google as the most visited US site in 2006.",
          "Bands used it as their primary distribution channel.",
        ],
        ["Inline CSS", "Flash", "Marquee"],
      ),
      era(
        2008,
        "http://www.myspace.com",
        "firefox",
        "Cleaner chrome, and the beginning of the end.",
        "Standardisation arrived, and the magic left.",
        "Tabs, tidier columns, muted blue.",
        "Facebook's consistency beat MySpace's chaos.",
        [
          "MySpace Music launched to compete with iTunes.",
          "Ad load grew heavier as growth slowed.",
          "By 2009 Facebook had overtaken it in the US.",
        ],
        ["CSS 2", "AJAX", "Flash"],
      ),
    ],
  },
  {
    id: "imdb",
    name: "IMDb",
    category: "knowledge",
    founded: "October 17, 1990",
    foundedYear: 1990,
    brand: "#f5c518",
    mark: "★",
    blurb: "A Usenet movie list that became the world's film ledger.",
    snapshots: [
      era(
        1996,
        "http://www.imdb.com",
        "netscape",
        "A text database with links, and nothing else.",
        "Film credits became searchable and cross-linked.",
        "Grey background, blue links, monospace tables.",
        "Hyperlinked credits invented the modern reference site.",
        [
          "IMDb began as a Usenet post of actresses with beautiful eyes.",
          "It ran on volunteer-maintained shell scripts for years.",
          "Amazon acquired it in 1998.",
        ],
        ["Perl", "HTML 2", "CGI"],
      ),
      era(
        2003,
        "http://www.imdb.com",
        "ie",
        "Yellow bars, star ratings and message boards.",
        "Community ratings became the headline number.",
        "Yellow-black chrome, dense tables, tiny Verdana.",
        "A single decimal number began deciding what people watched.",
        [
          "The Top 250 became a canonical film list.",
          "Message boards ran for fifteen years before closing.",
          "The rating was a weighted average, never a plain mean.",
        ],
        ["Tables", "Perl", "CSS 1"],
      ),
      era(
        2014,
        "http://www.imdb.com",
        "chrome",
        "Poster-led layouts and trailer players.",
        "Images finally outranked text.",
        "Poster grids, dark headers, gold accents.",
        "Reference sites became media sites.",
        [
          "Trailers became a primary reason to visit.",
          "The gold and black palette was formalised.",
          "Mobile traffic overtook desktop during this period.",
        ],
        ["Responsive", "CSS 3", "HTML5 Video"],
      ),
      era(
        2026,
        "https://www.imdb.com",
        "edge",
        "Dark cinematic surfaces, watch-anywhere links.",
        "Availability data sits next to every title.",
        "Dark UI, gold highlights, card rows.",
        "The ledger became a shopping guide for streaming.",
        [
          "Streaming availability is shown per region.",
          "Ratings remain the most-cited number in film discourse.",
          "The gold star is one of the web's oldest surviving marks.",
        ],
        ["React", "CSS Grid", "Dark Mode"],
      ),
    ],
  },
];

export interface Milestone {
  year: number;
  title: string;
  body: string;
}

export const MILESTONES: Milestone[] = [
  { year: 1995, title: "The web goes commercial", body: "Netscape's IPO sets off the dot-com boom." },
  { year: 1998, title: "Google launches", body: "Two Stanford students index the web with PageRank." },
  { year: 2001, title: "Wikipedia launches", body: "Anyone can edit the encyclopedia. Chaos, then order." },
  { year: 2004, title: "Facebook opens", body: "Social networking moves from novelty to infrastructure." },
  { year: 2005, title: "YouTube is born", body: "Video stops being a download and becomes a page." },
  { year: 2007, title: "The iPhone lands", body: "Mobile browsing forces the web to become responsive." },
  { year: 2010, title: "Modern web design begins", body: "Media queries replace the separate m-dot website." },
  { year: 2015, title: "Responsive becomes standard", body: "Mobile-first indexing makes it a ranking factor." },
  { year: 2020, title: "Web apps dominate", body: "Components, dark mode and design systems everywhere." },
  { year: 2026, title: "AI-native interfaces", body: "Answers arrive before the links finish loading." },
];

export function getSite(id: string): SiteDef {
  return SITES.find((s) => s.id === id) ?? SITES[0];
}

export function nearestSnapshot(site: SiteDef, year: number): EraSnapshot {
  return site.snapshots.reduce((best, s) =>
    Math.abs(s.year - year) < Math.abs(best.year - year) ? s : best,
  );
}

export function browserForYear(year: number): BrowserKind {
  if (year < 1999) return "netscape";
  if (year < 2007) return "ie";
  if (year < 2011) return "firefox";
  if (year < 2022) return "chrome";
  return "edge";
}

export const TIMELINE_YEARS = [1995, 2000, 2005, 2010, 2015, 2020, 2026];
export const YEAR_MIN = 1995;
export const YEAR_MAX = 2026;
export const TOTAL_ERAS = SITES.reduce((n, s) => n + s.snapshots.length, 0);
